config/routes.rb
Rails.application.routes.draw do
  resources :post_dates
  get 'sessions/new'
  resources :users
  resources :petrol_stations do
    resources :post_dates, only: [:new, :create, :edit, :update, :show, :destroy] do
      resources :posts, only: [:new, :create, :edit, :update, :show, :destroy]
    end
  end
  
  root to: 'static#index'
  get '/api' => redirect('/swagger/dist/index.html?url=/api-docs.json')

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  get    '/feed',   to: 'static#feed'

end

app/models/petrol_station.rb
class PetrolStation < ApplicationRecord
    has_and_belongs_to_many :users, :join_table => :users_petrol_stations
    has_many :post_date
end

app/controllers/petrol_stations_controller.rb
class PetrolStationsController < ApplicationController
  before_action :set_petrol_station, only: %i[ show edit update destroy ]
  swagger_controller :petrol_stations, 'Petrol Stations'

  swagger_api :index do
    summary 'Returns all petrol stations'
    notes 'Notes...'
  end
  def index
    @petrol_stations = PetrolStation.all
  end

  swagger_api :show do
    summary 'Returns one petrol station'
    param :path, :id, :integer, :required, "Petrol Station id"
    notes 'Notes...'
  end
  def show
  end

  def new
    @petrol_station = PetrolStation.new
  end

  def edit
  end

  swagger_api :create do
    summary "Create a petrol station"
    param :form, "petrol_station[name]", :string, :required, "Petrol Station name"
    param :form, "petrol_station[address]", :string, :required, "Petrol Station address"
  end
  def create
    @petrol_station = PetrolStation.new(petrol_station_params)

    respond_to do |format|
      if @petrol_station.save
        format.html { redirect_to petrol_station_url(@petrol_station), notice: "Petrol station was successfully created." }
        format.json { render :show, status: :created, location: @petrol_station }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @petrol_station.errors, status: :unprocessable_entity }
      end
    end
  end


  swagger_api :update do
    summary "Update a petrol station"
    param :path, :id, :integer, :required, "Petrol Station id"
    param :form, "petrol_station[name]", :string, :required, "Petrol Station name"
    param :form, "petrol_station[address]", :string, :required, "Petrol Station address"
  end
  def update
    respond_to do |format|
      if @petrol_station.update(petrol_station_params)
        format.html { redirect_to petrol_station_url(@petrol_station), notice: "Petrol station was successfully updated." }
        format.json { render :show, status: :ok, location: @petrol_station }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @petrol_station.errors, status: :unprocessable_entity }
      end
    end
  end

  swagger_api :destroy do
    summary 'Destroys a petrol station'
    param :path, :id, :integer, :required, "Petrol Station id"
    notes 'Notes...'
  end
  def destroy
    @petrol_station.destroy

    respond_to do |format|
      format.html { redirect_to petrol_stations_url, notice: "Petrol station was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_petrol_station
      @petrol_station = PetrolStation.find(params[:id])
    end

    def petrol_station_params
      params.require(:petrol_station).permit(:name, :address)
    end
end

app/helpers/petrol_stations_helper.rb
module PetrolStationsHelper
end

app/views/petrol_stations/_form.html.erb
<%= form_with(model: petrol_station) do |form| %>
  <% if petrol_station.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(petrol_station.errors.count, "error") %> prohibited this petrol_station from being saved:</h2>

      <ul>
        <% petrol_station.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/petrol_stations/_petrol_station.html.erb
<div id="<%= dom_id petrol_station %>">
  <p>
    <strong>Nazwa:</strong>
    <%= petrol_station.name %>
  </p>

  <p>
    <strong>Adres:</strong>
    <%= petrol_station.address %>
  </p>



</div>

app/views/petrol_stations/edit.html.erb
<h1>Editing petrol station</h1>

<%= render "form", petrol_station: @petrol_station %>

<br>

<div>
  <%= link_to "Show this petrol station", @petrol_station %> |
  <%= link_to "Back to petrol stations", petrol_stations_path %>
</div>

app/views/petrol_stations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Petrol stations</h1>

<div id="petrol_stations">
  <% @petrol_stations.each do |petrol_station| %>
    <%= render petrol_station %>
    <p>
      <%= link_to "Show this petrol station", petrol_station %>
    </p>
  <% end %>
</div>

<%= link_to "New petrol station", new_petrol_station_path %>

app/views/petrol_stations/new.html.erb
<h1>New petrol station</h1>

<%= render "form", petrol_station: @petrol_station %>

<br>

<div>
  <%= link_to "Back to petrol stations", petrol_stations_path %>
</div>

app/views/petrol_stations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @petrol_station %>

  <h1>Kalendarz</h1>
  <%#W przypadku .post_dates wyskakuje błąd na /petrol-station/X %>
  <%#W przypadku .postdate wyskakuje błąd na /petrol-station/X/post_dates/new %>
<% if @petrol_station.post_date.length == 0 %>
  Nie ma żadnych wpisów
<% else %>
  <% @petrol_station.post_date.each do |post_date| %>
    <%= link_to [@petrol_station, post_date] do %>
    <h4><%= post_date.title %> </h4>
    <% end %>
  <% end %>
<% end %>

<hr>

<% if logged_in? %>
  <%= link_to "Dodaj datę", new_petrol_station_post_date_path(@petrol_station) %>
<% end %>

<%# <div> %>
  <%# <%= link_to "Edit this petrol station", edit_petrol_station_path(@petrol_station) %> 
  <%# <%= link_to "Back to petrol stations", petrol_stations_path %>

  <%# <%= button_to "Destroy this petrol station", @petrol_station, method: :delete %>
<%# </div> %>