config/routes.rb
Rails.application.routes.draw do
  resources :post_dates
  get 'sessions/new'
  resources :users
  resources :petrol_stations do
    resources :post_dates, only: [:new, :create, :edit, :update, :show, :destroy] do
      resources :posts, only: [:new, :create, :edit, :update, :show, :destroy]
    end
  end
  
  root to: 'static#index'
  get '/api' => redirect('/swagger/dist/index.html?url=/api-docs.json')

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  get    '/feed',   to: 'static#feed'

end

app/models/post_date.rb
class PostDate < ApplicationRecord
  belongs_to :user
  belongs_to :petrol_station
  has_many :posts
end

app/controllers/post_dates_controller.rb
class PostDatesController < ApplicationController
  before_action :set_post_date, only: %i[show edit update destroy ]

  swagger_controller :post_dates, 'Post Dates'

  swagger_api :index do
    summary 'Returns all post dates'
    notes 'Notes...'
  end
  def index
    @post_dates = PostDate.all
  end

  swagger_api :show do
    summary 'Returns one post date'
    param :path, :petrol_station_id, :integer, :required, "Petrol Station id"
    param :path, :id, :integer, :required, "Post date id"
    notes 'Notes...'
  end
  def show
  end

  def new
    @petrol_station = PetrolStation.find(params[:petrol_station_id])
    # tutaj występuje bład, gdy dam post_dates ! - podczas "Dodaj datę"
    @post_date = @petrol_station.post_date.new
  end

  def edit
  end

  swagger_api :create do
    summary "Create new post date"
    param :header, "Authorization", :string, :required, "Authentication token"
    param :path, :petrol_station_id, :integer, :required, "Petrol Station id"
    param :form, "post_date[title]", :string, :required, "Title of a post date"
  end
  def create
    @petrol_station = PetrolStation.find(params[:petrol_station_id])
    # tutaj występuje błąd, gdy ustawie @petrol_station.post_dates.new - po zakończeniu tworzenia "PostDate", czyt. uzupełnisz dane i klikasz "Create Post date"
    # błąd: undefined method `post_dates' for #<PetrolStation id: 1, name: "Orlen (Szybowcowa)", address: "ul. Szybowcowa 27, Wrocław", created_at: "2022-05-04 19:37:53.821037000 +0000", updated_at: "2022-05-04 19:37:53.821037000 +0000">
    @post_date = @petrol_station.post_date.new(post_date_params)
    @post_date.user = current_user
  
    respond_to do |format|
      if @post_date.save
        format.html { redirect_to [@petrol_station, @post_date], notice: 'post_date was successfully created.' }
        format.json { render :show, status: :created, location: @post_date }
      else
        format.html { render :new }
        format.json { render json: @post_date.errors, status: :unprocessable_entity }
      end
    end
  end

  swagger_api :update do
    summary "Update a post date"
    param :path, :id, :integer, :required, "Post date id"
    param :path, :petrol_station_id, :integer, :required, "Petrol Station id"
    param :form, "post_date[title]", :string, :required, "Post date title"
  end
  def update
    respond_to do |format|
      if @post_date.update(post_date_params)
        format.html { redirect_to [@petrol_station, @post_date], notice: 'post_date was successfully updated.' }
        format.json { render :show, status: :ok, location: @post_date }
      else
        format.html { render :edit }
        format.json { render json: @post_date.errors, status: :unprocessable_entity }
      end
    end
  end


  swagger_api :destroy do
    summary 'Destroys a post date'
    param :path, :id, :integer, :required, "Post date id"
    param :path, :petrol_station_id, :integer, :required, "Petrol Station id"
    notes 'Notes...'
  end
  def destroy
    @post_date.destroy

    respond_to do |format|
      format.html { redirect_to post_dates_url, notice: "Post date was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_post_date
      @petrol_station = PetrolStation.find(params[:petrol_station_id])
      @post_date = PostDate.find(params[:id])
    end

    def post_date_params
      params.require(:post_date).permit(:title, :user_id, :petrol_station_id)
    end
end

app/helpers/post_dates_helper.rb
module PostDatesHelper
end

app/views/post_dates/_form.html.erb
<%= form_for [@petrol_station, @post_date] do |form| %>
  <% if post_date.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post_date.errors.count, "error") %> prohibited this post_date from being saved:</h2>

      <ul>
        <% post_date.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :petrol_station_id, style: "display: block" %>
    <%= form.text_field :petrol_station_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/post_dates/_post_date.html.erb
<p id="notice"><%= notice %></p>

app/views/post_dates/edit.html.erb
<h1>Editing post date</h1>

<%= render 'form', post_date: @post_date %>
<%# <%= link_to 'Show', @post_dates %> 
<%= link_to 'Back', @petrol_station %>

app/views/post_dates/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Post dates</h1>

<div id="post_dates">
  <% @post_dates.each do |post_date| %>
    <%= render post_date %>
    <p>
      <%= link_to post_date.title, post_date %>
    </p>
  <% end %>
</div>

<%= link_to "New post date", new_post_date_path %>

app/views/post_dates/new.html.erb
<h1>New Topic</h1>

<%= render 'form', post_date: @post_date %>

<%= link_to 'Back', @petrol_station %>

app/views/post_dates/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post_date %>

<h1><%= @post_date.title %> 
<h2><%= link_to @petrol_station.name, @petrol_station %></h2>

<h3><%= link_to "Dodaj cenę", new_petrol_station_post_date_post_path(@petrol_station,@post_date) %></h3>

<hr>
<h1>Dzisiejsze ceny</h1>
<% if @post_date.posts.length == 0 %>
  Brak wpisów
<% else %>
  <ul>
  <% @post_date.posts.each do |post| %>
    <li>
      <strong><%= post.user.name %> wprowadził cene benzyny:</strong> <%= post.pb_price %>
      <strong><%= post.user.name %> wprowadził cene diesel-a:</strong> <%= post.diesel_price %>
    </li>
  <% end %>
  </ul>
<% end %>

<p>
  <%= link_to 'Edit', edit_petrol_station_post_date_path(@petrol_station, @post_date) %> |
  <%= link_to 'Back', @petrol_station %>
</p>