config/routes.rb
Rails.application.routes.draw do
  resources :post_dates
  get 'sessions/new'
  resources :users
  resources :petrol_stations do
    resources :post_dates, only: [:new, :create, :edit, :update, :show, :destroy] do
      resources :posts, only: [:new, :create, :edit, :update, :show, :destroy]
    end
  end
  
  root to: 'static#index'
  get '/api' => redirect('/swagger/dist/index.html?url=/api-docs.json')

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  get    '/feed',   to: 'static#feed'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<title>System informowania o cenach paliw</title>
<meta property="og:title" content="System informowania o cenach paliw" />

  <head>
    <title>AplikacjeMobilne</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <ul>
      MENU
      <li><%= link_to "Strona główna", root_path %></li>
      <li><%= link_to "Uzytkownicy", users_path %></li>
      <li><%= link_to "Stacje paliw", petrol_stations_path %></li>
      <% if logged_in? %>
        <li><%= button_to 'Wyloguj', logout_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Zaloguj", login_path %></li>
      <% end %>
    </ul>
  </head>

  <body>

    <%= yield %>
  </body>
</html>